In [109]:
mylist = [1,2,3,4,5,6,7,8,9,10]

In [110]:
for item in mylist:
    print("LA LA LA LA")

LA LA LA LA
LA LA LA LA
LA LA LA LA
LA LA LA LA
LA LA LA LA
LA LA LA LA
LA LA LA LA
LA LA LA LA
LA LA LA LA
LA LA LA LA


In [112]:
for item in mylist:
    if item %2 == 0:
        print(item)
    else:
        print("ODD")

ODD
2
ODD
4
ODD
6
ODD
8
ODD
10


In [114]:
for _ in "Hello owrld":
    print("asdsdsad")
    

asdsdsad
asdsdsad
asdsdsad
asdsdsad
asdsdsad
asdsdsad
asdsdsad
asdsdsad
asdsdsad
asdsdsad
asdsdsad


In [115]:
len(mylist)

10

In [118]:
mylist[9] = 'new item'

In [119]:
mylisttuples = [(1,2),(3,4),(4,5)]
for item in mylisttuples:
    print(item)

(1, 2)
(3, 4)
(4, 5)


In [122]:
for (_,_) in mylisttuples:
    print(x,y)

4 5
4 5
4 5


In [127]:
mydict = {'k1':1,'k2':2}
for item in mydict.items():
    print(item)

('k1', 1)
('k2', 2)


In [130]:
count = 1
for i in range(10):
    print(str(i)* i)
    for j in range(0,i):
        count = count+1


1
22
333
4444
55555
666666
7777777
88888888
999999999


In [131]:
for i in range(1,3):
    for j in range(1,2):
        print("*")

*
*


In [137]:
x = 0
while x<5:
    print('valueof x is:', x)
    x = x+1
else:
    print('oops!!')

valueof x is: 0
valueof x is: 1
valueof x is: 2
valueof x is: 3
valueof x is: 4
oops!!


In [150]:
x=[1,2,3]
for item in x:
    pass
    print("item")
print("end of for loop")

item
item
item
end of for loop


In [140]:
mystring = "python"
for letter in mystring:
    print(letter)

p
y
t
h
o
n


In [145]:
for letter in mystring:
    if letter =='p':
        continue
    print(letter)
print("YAYY")

y
t
h
o
n
YAYY


In [147]:
for letter in mystring:
    if letter == 'o':
        break
    print(letter)
print("YOYOH")

p
y
t
h
YOYOH


In [151]:
numitem = 1
numitem/0

ZeroDivisionError: division by zero

In [152]:
num1 = 10
num2=input("pleas gimme a num:")

pleas gimme a num:wqe


In [154]:
try:
    result = 10 +'50'
except:
    print("Please correct")
else:
    print("result")
finally:
    print("HEy")

Please correct
HEy


In [155]:
import numpy as np


In [156]:
np.zeros(2)

array([0., 0.])

In [157]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [159]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [167]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [169]:
np.ones((2,3))*5

array([[5., 5., 5.],
       [5., 5., 5.]])

In [170]:
x = [[1,2],[3,4],[5,6]]

In [175]:
np.linspace(1,3,2)

array([1., 3.])

In [176]:
np.linspace(1,50)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [177]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [201]:
arr1 = np.random.rand(4,3)

In [203]:
arr1.argmax()

7

In [185]:
np.random.randn(1,10)

array([[-0.96177385, -0.63787798, -2.67656012, -0.901644  , -0.71107695,
         1.18681332, -0.78502774,  0.75448812,  0.80565018, -1.26863504]])

In [189]:
arr = np.arange(20)


In [190]:
arr.ndim

1

In [191]:
len(arr)

20

In [196]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 20 into shape (3,3)

In [205]:
arr = np.arange(1,10)
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9])

In [209]:
arrcond = arr[arr >5]
arrcond

array([100, 100, 100, 100, 100,   6,   7,   8,   9])

In [210]:
my_new_data = np.arange(25)

In [212]:
my_new_data(4,4)

NameError: name 'my_new_data94' is not defined

In [15]:
%hist -o -g -f ipython_history_2.md